## makeCacheMatrix() stores a list of functions, which either caches the 
## values of or retrieve the cached values of a matrix and its inverse 
## cacheSolve() takes a list generated by makeCacheMatrix() as input, 
## and if the inverse of the matrix has already been computed and cached,
## retrieves its value, and if not, computes the inverse, caches it, and 
## returns it.


## makeCacheMatrix() creates a matrix which can be cached, and whose inverse
## can also be cached

makeCacheMatrix <- function(x = matrix()) {
	 i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinv <- function(inv) i <<- inv
        getinv <- function() i
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)

}


## takes a list generated by makeCacheMatrix as input, and calculates and 
## caches its inverse if it hasn't been calculated yet. If it has already 
## been calculated, it merely retrieves the inverse

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'

        i <- x$getinv()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data)
        x$setinv(i)
        i


}
